// src/app/[lang]/rephrase/page.tsx
'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useTranslations } from 'next-intl';
import { deckMetadata } from '@/data/decks';
import LevelFilterChips from '@/components/LevelFilterChips';
import { useSRS } from '@/hooks/useSRS';
import { useLevelFilter } from '@/hooks/useLevelFilter';
import { DECK_MAP } from '@/data/deckMap';
import type { Card, DeckId, Lang, Level } from '@/types';

// Note: generateStaticParams for [lang]/rephrase is in layout.tsx
// 'use client' and generateStaticParams cannot coexist on a page file.

interface DeckGridProps {
  lang: Lang;
  activeLevels: Level[];
  isCardDueForDeck: (deckId: DeckId, cardIndex: number) => boolean;
}

function DeckGrid({ lang, activeLevels, isCardDueForDeck }: DeckGridProps) {
  const t = useTranslations('decks');
  const td = useTranslations('deckDescriptions');

  const decks = deckMetadata.filter((d) => d.lang === lang);

  function getDueCount(deckId: DeckId, cards: Card[]): number {
    return cards
      .map((card, i) => ({ card, i }))
      .filter(({ card }) => (activeLevels as Level[]).includes(card.level))
      .filter(({ i }) => isCardDueForDeck(deckId, i))
      .length;
  }

  return (
    <div className="deck-grid">
      {decks.map((deck) => {
        const deckCards = DECK_MAP[lang]?.[deck.id] ?? [];
        const due = getDueCount(deck.id, deckCards);
        return (
          <Link
            key={deck.id}
            href={`/${lang}/rephrase/${deck.id}`}
            style={{ textDecoration: 'none', display: 'block', height: '100%' }}
          >
            <div className={`deck-card theme-${deck.theme}`} style={{ height: '100%' }}>
              <div className="deck-icon-circle">{deck.icon}</div>
              <h3>{t(deck.i18nKey)}</h3>
              <p>{td(deck.i18nKey)}</p>
              <span className={`deck-card-badge${due === 0 ? ' deck-card-badge--done' : ''}`}>
                {due === 0 ? '✓' : due}
              </span>
            </div>
          </Link>
        );
      })}
    </div>
  );
}

export default function LangPage() {
  const params = useParams<{ lang: string }>();
  const lang = params.lang as Lang;
  const t = useTranslations('page');
  const { isCardDueForDeck, hasProgress } = useSRS(lang);
  const { activeLevels, setActiveLevels } = useLevelFilter(lang, hasProgress);

  return (
    <main>
      <div className="section-header">
        <h1>{t('title')}</h1>
        <p className="subtitle">{t('subtitle')}</p>
      </div>
      <LevelFilterChips lang={lang} activeLevels={activeLevels} setActiveLevels={setActiveLevels} />
      <DeckGrid lang={lang} activeLevels={activeLevels} isCardDueForDeck={isCardDueForDeck} />
    </main>
  );
}

// app/pages/rephrase/index.vue
<script setup lang="ts">
import { deckMetadata } from '~/data/decks'
import { DECK_MAP } from '~/data/deckMap'
import type { Card, DeckId } from '~/types'

const { t, locale } = useI18n()
const lang = computed(() => locale.value as 'it' | 'es')

const { isCardDueForDeck, hasProgress } = useSRS(lang.value)
const { activeLevels, setActiveLevels } = useLevelFilter(lang.value, hasProgress)

const decks = computed(() => deckMetadata.filter(d => d.lang === lang.value))

function getDueCount(deckId: DeckId, cards: Card[]): number {
  if (!activeLevels.value) return 0
  return cards.filter((card, i) =>
    activeLevels.value!.includes(card.level) && isCardDueForDeck(deckId, i)
  ).length
}

const deckDueCounts = computed(() =>
  Object.fromEntries(
    decks.value.map(deck => {
      const cards = DECK_MAP[lang.value]?.[deck.id] ?? []
      return [deck.id, getDueCount(deck.id, cards)]
    })
  )
)
</script>

<template>
  <main>
    <h1>{{ t('page.chooseDeck') }}</h1>

    <div data-level-filter>
      <LevelFilterChips
        :active-levels="activeLevels ?? []"
        @update:active-levels="setActiveLevels"
      />
    </div>

    <div class="deck-grid">
      <NuxtLinkLocale
        v-for="deck in decks"
        :key="deck.id"
        :to="'/rephrase/' + deck.id"
      >
        <div :class="['deck-card', 'theme-' + deck.theme]">
          <div class="deck-icon-circle">{{ deck.icon }}</div>
          <h3>{{ t('decks.' + deck.i18nKey) }}</h3>
          <p>{{ t('deckDescriptions.' + deck.i18nKey) }}</p>
          <span
            :class="['deck-card-badge', deckDueCounts[deck.id] === 0 ? 'deck-card-badge--done' : '']"
          >{{ deckDueCounts[deck.id] === 0 ? '✓' : deckDueCounts[deck.id] }}</span>
        </div>
      </NuxtLinkLocale>
    </div>
  </main>
</template>
