// app/components/ChoiceButton.vue
<script setup lang="ts">
defineProps<{
  text: string
  state: 'idle' | 'correct' | 'incorrect'
  disabled?: boolean
}>()

const emit = defineEmits<{
  click: []
  speak: []
}>()
</script>

<template>
  <button
    type="button"
    :disabled="disabled || state !== 'idle'"
    :class="['quiz-btn', { [state]: state !== 'idle' }]"
    @click="emit('click')"
  >
    <span
      role="button"
      class="quiz-audio-icon"
      data-speaker
      :tabindex="0"
      @click.stop="emit('speak')"
      @keydown.enter.stop="emit('speak')"
      @keydown.space.stop="emit('speak')"
    >🔊</span>
    {{ text }}
  </button>
</template>

// src/components/ChoiceButton.tsx
'use client';

interface Props {
  text: string;
  state: 'idle' | 'correct' | 'incorrect';
  onClick: () => void;
  disabled?: boolean;
  onSpeak?: () => void;
}

export default function ChoiceButton({ text, state, onClick, disabled, onSpeak }: Props) {
  const classNames = ['quiz-btn', state !== 'idle' ? state : ''].filter(Boolean).join(' ');

  return (
    <button
      className={classNames}
      onClick={onClick}
      disabled={disabled || state !== 'idle'}
      type="button"
    >
      <span
        className="quiz-audio-icon"
        role="button"
        aria-label="audio"
        tabIndex={0}
        onClick={(e) => {
          e.stopPropagation();
          onSpeak?.();
        }}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.stopPropagation();
            onSpeak?.();
          }
        }}
      >
        🔊
      </span>
      {text}
    </button>
  );
}
