// app/components/MicButton.vue
<script setup lang="ts">
defineProps<{
  state: 'idle' | 'listening' | 'error'
}>()

const emit = defineEmits<{
  press: []
}>()
</script>

<template>
  <button
    type="button"
    :class="`mic-btn${state !== 'idle' ? ` mic-btn--${state}` : ''}`"
    :aria-label="state === 'listening' ? 'Listening\u2026' : 'Start speaking'"
    :aria-pressed="state === 'listening'"
    @click.stop="emit('press')"
  >🎙</button>
</template>

// src/components/MicButton.tsx
'use client';

interface Props {
  state: 'idle' | 'listening' | 'error';
  onPress: () => void;
}

export default function MicButton({ state, onPress }: Props) {
  const baseClass = 'mic-btn';
  const stateClass = state !== 'idle' ? ` mic-btn--${state}` : '';

  return (
    <button
      type="button"
      className={`${baseClass}${stateClass}`}
      onClick={(e) => { e.stopPropagation(); onPress(); }}
      aria-label={state === 'listening' ? 'Listening\u2026' : 'Start speaking'}
      aria-pressed={state === 'listening'}
    >
      {'\uD83C\uDF99'}
    </button>
  );
}
